
services:
  api-gateway:
    build: ./api-gateway
    image: richwell111/api-gateway:latest
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  identity-service:
    build: ./identity-service
    image: richwell111/identity-service:latest
    env_file: ./identity-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  post-service:
    build: ./post-service
    image: richwell111/post-service:latest
    env_file: ./post-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  media-service:
    build: ./media-service
    image: richwell111/media-service:latest
    env_file: ./media-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  search-service:
    build: ./search-service
    image: richwell111/search-service:latest
    env_file: ./search-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
